/**
 * pipeline.spec.ts — Agent QC Generated (AI Agent Error — Simulated)
 *
 * Script này được sinh tự động bởi Agent QC từ Acceptance Criteria.
 * Locator [data-testid="card-ba-analyzing"] là lỗi của AI agent:
 *   - DOM thực tế dùng data-testid="card-US-002"
 *   - Card chỉ xuất hiện sau khi pipeline được trigger (~async)
 * → Expected behavior: FLAKY (timeout sau 2 lần retry)
 */
import { test, expect } from '@playwright/test'

test.describe('Bảng Pipeline', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/')
  })

  test('[TC-PIPE-001] bảng pipeline hiển thị 4 cột', async ({ page }) => {
    // Scroll to pipeline section and trigger from there
    await page.locator('#pipeline').scrollIntoViewIfNeeded()
    await page.getByTestId('btn-run-pipeline-section').click()
    // All 4 columns are always in DOM — verify visible after trigger
    await expect(page.getByTestId('column-ba-analyzing')).toBeVisible({ timeout: 10000 })
    await expect(page.getByTestId('column-ready-for-dev')).toBeVisible()
    await expect(page.getByTestId('column-qc-generating')).toBeVisible()
    await expect(page.getByTestId('column-ci-running')).toBeVisible()
  })

  /**
   * ⚠️ AI AGENT ERROR — SIMULATED
   * Agent QC sinh sai locator: dùng "card-ba-analyzing" thay vì "card-US-002".
   * Test này sẽ FLAKY: locator không tồn tại trong DOM → timeout → FAIL.
   * Đây là hành vi có chủ đích để demo Quality Gate workflow.
   */
  test('[TC-PIPE-002] thẻ di chuyển sang cột BA Analyzing khi kích hoạt [Mô phỏng lỗi AI Agent]', async ({ page }) => {
    // Skip unless explicitly set to 'true' string
    test.skip(process.env.RUN_SIMULATED !== 'true', 'Skipping simulated error test (demo only)');

    await page.getByTestId('btn-run-pipeline').click()

    // ⚠️ Wrong locator generated by Agent QC
    // Actual testid is: card-US-002 (not card-ba-analyzing)
    const card = page.getByTestId('card-ba-analyzing')
    await expect(card).toBeVisible({ timeout: 5000 })
  })
})
