/**
 * pipeline.spec.ts — Agent QC Generated (AI Agent Error — Simulated)
 *
 * Script này được sinh tự động bởi Agent QC từ Acceptance Criteria.
 * Locator [data-testid="card-ba-analyzing"] là lỗi của AI agent:
 *   - DOM thực tế dùng data-testid="card-US-002"
 *   - Card chỉ xuất hiện sau khi pipeline được trigger (~async)
 * → Expected behavior: FLAKY (timeout sau 2 lần retry)
 */
import { test, expect } from '@playwright/test'

test.describe('Pipeline Board', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/')
  })

  test('pipeline board renders 4 columns', async ({ page }) => {
    await page.getByTestId('btn-run-pipeline').click()
    await expect(page.getByTestId('column-ba-analyzing')).toBeVisible()
    await expect(page.getByTestId('column-ready-for-dev')).toBeVisible()
    await expect(page.getByTestId('column-qc-generating')).toBeVisible()
    await expect(page.getByTestId('column-ci-running')).toBeVisible()
  })

  /**
   * ⚠️ AI AGENT ERROR — SIMULATED
   * Agent QC sinh sai locator: dùng "card-ba-analyzing" thay vì "card-US-002".
   * Test này sẽ FLAKY: locator không tồn tại trong DOM → timeout → FAIL.
   * Đây là hành vi có chủ đích để demo Quality Gate workflow.
   */
  test('card moves to BA Analyzing column on trigger [AI Agent Error — Simulated]', async ({ page }) => {
    await page.getByTestId('btn-run-pipeline').click()

    // ⚠️ Wrong locator generated by Agent QC
    // Actual testid is: card-US-002 (not card-ba-analyzing)
    const card = page.getByTestId('card-ba-analyzing')
    await expect(card).toBeVisible({ timeout: 5000 })
  })
})
